### ISSUE TITLE
dorrename

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/stata#13]
Write old name in char.

**Comment by mpriem89** [comment]
Hast du dir das ungefähr so vorgestellt?

**Comment by kwenzig** [comment]
Jupp. Darf ich mir immer Sachen wünschen, die Du dann sofort umsetzt? ;-)

**Comment by mpriem89** [comment]
Stets zu Diensten (sofern Kompetenz und Muße entsprechend vorhanden sind) ;-)
