### ISSUE TITLE
dorrename: local idataset & local istudy not defined

### ISSUE THREAD

**Issue by castolpe** [ddionrails/stata#5]
`local istudy : char _dta[study]`
`local iversion : char _dta[version]`

Woher sollen [study] und [version] kommen ? 
Wenn die Locals leer sind (Achtung: keine Fehlermeldung) funktioniert auch der Rest nicht mehr.

**Comment by kwenzig** [comment]
Sollen übergeben werden, inden die Datensätze das entsprechende characteristic bekommen, also, beispielsweise:

```
char _dta[study] "soep-fid"
char _dta[dataset] "f10h"
char _dta[dataset] "4.0"
```

Der Datensatz "weiß" also was über sich und damit kann man die Anzahl der zu übergebenden Parameter in der Folge reduzieren.
